### ISSUE TITLE
Failing specs

### ISSUE THREAD

**Issue by gdonald** [hanami/guides#222]
I just went through the 2.1 guide and built the bookshelf app.  At the end I am left with two failing specs:

```
Failures:

  1) Bookshelf::Actions::Books::Show works
     Failure/Error: expect(response).to be_successful
       expected `#<Hanami::Action::Response:0x0000000105142778 @status=404, @headers={"X-Frame-Options"=>"DENY", "X-Co...tml; charset=utf-8", "Content-Length"=>"9"}, @cookies={}, @default_options={}, @changes=#<Set: {}>>>.successful?` to be truthy, got false
     # ./spec/actions/books/show_spec.rb:8:in `block (2 levels) in <top (required)>'

  2) Books index shows a list of books
     Failure/Error: expect(page).to have_selector('li', text: 'Test Driven Development, by Kent Beck')
       expected to find visible css "li" with text "Test Driven Development, by Kent Beck" but there were no matches. Also found "Book 0, by Author 0", "Book 1, by Author 1", "Book 2, by Author 2", "Book 3, by Author 3", "Book 4, by Author 4", which matched the selector but not all filters.
     # ./spec/features/books/index_spec.rb:12:in `block (2 levels) in <top (required)>'

Finished in 0.12192 seconds (files took 0.42028 seconds to load)
12 examples, 2 failures

Failed examples:

rspec ./spec/actions/books/show_spec.rb:6 # Bookshelf::Actions::Books::Show works
rspec ./spec/features/books/index_spec.rb:9 # Books index shows a list of books
```

**Comment by gdonald** [comment]
Closing due to lack of interest.
