### ISSUE TITLE
Wrong number of aarguments issue

### ISSUE THREAD

**Issue by Naniakl3** [hanami/guides#31]
Hi All, am using hanami 1.3.1 and ruby version is 2.3.0. when i am trying to create new application it shows "wrong number of arguments (given 0, expected 2..3)" error.

**Comment by davydovanton** [comment]
hey @Naniakl3, thanks for your report!

Could you please share stacktrace (full error message) in gist file and also say what you'll get after call `hanami --version`

**Comment by adam12** [comment]
Closing due to lack of feedback. If this is still affecting you, please feel free to update this issue with the requested information.

**Comment by senid231** [comment]
still does not work

```
$ rvm use 3.0.3@hanami_app --create
$ gem install bundler
$ gem install hanami
$ hanami --version
/home/senid/.rvm/gems/ruby-3.0.3@virtualizm/gems/dry-types-0.12.3/lib/dry/types/definition.rb:33:in `initialize': wrong number of arguments (given 3, expected 1..2) (ArgumentError)
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/gems/dry-types-0.12.3/lib/dry/types/options.rb:17:in `new'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/gems/dry-types-0.12.3/lib/dry/types/options.rb:17:in `with'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/gems/dry-types-0.12.3/lib/dry/types/builder.rb:59:in `constructor'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/gems/dry-types-0.12.3/lib/dry/types/core.rb:41:in `block in <module:Types>'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/gems/dry-types-0.12.3/lib/dry/types/core.rb:40:in `each'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/gems/dry-types-0.12.3/lib/dry/types/core.rb:40:in `<module:Types>'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/gems/dry-types-0.12.3/lib/dry/types/core.rb:4:in `<module:Dry>'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/gems/dry-types-0.12.3/lib/dry/types/core.rb:3:in `<top (required)>'
        from <internal:/home/senid/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/senid/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/gems/dry-types-0.12.3/lib/dry/types.rb:158:in `<top (required)>'
        from <internal:/home/senid/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/senid/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/gems/dry-validation-0.11.2/lib/dry/validation/input_processor_compiler.rb:1:in `<top (required)>'
        from <internal:/home/senid/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/senid/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/gems/dry-validation-0.11.2/lib/dry/validation/schema/deprecated.rb:1:in `<top (required)>'
        from <internal:/home/senid/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/senid/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/gems/dry-validation-0.11.2/lib/dry/validation/schema.rb:14:in `<top (required)>'
        from <internal:/home/senid/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/senid/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/gems/dry-validation-0.11.2/lib/dry/validation.rb:39:in `<top (required)>'
        from <internal:/home/senid/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/senid/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/gems/dry-validation-0.11.2/lib/dry-validation.rb:1:in `<top (required)>'
        from <internal:/home/senid/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/senid/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/gems/hanami-validations-1.3.8/lib/hanami/validations.rb:3:in `<top (required)>'
        from <internal:/home/senid/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/senid/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/gems/hanami-1.3.4/lib/hanami/frameworks.rb:2:in `<top (required)>'
        from <internal:/home/senid/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/senid/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/gems/hanami-1.3.4/lib/hanami.rb:10:in `<module:Hanami>'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/gems/hanami-1.3.4/lib/hanami.rb:8:in `<top (required)>'
        from <internal:/home/senid/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/senid/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/gems/hanami-1.3.4/lib/hanami/cli/commands/command.rb:1:in `<top (required)>'
        from <internal:/home/senid/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/senid/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/gems/hanami-1.3.4/lib/hanami/cli/commands.rb:89:in `<module:Commands>'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/gems/hanami-1.3.4/lib/hanami/cli/commands.rb:56:in `<class:CLI>'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/gems/hanami-1.3.4/lib/hanami/cli/commands.rb:8:in `<module:Hanami>'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/gems/hanami-1.3.4/lib/hanami/cli/commands.rb:4:in `<top (required)>'
        from <internal:/home/senid/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/senid/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/gems/hanami-1.3.4/bin/hanami:3:in `<top (required)>'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/bin/hanami:25:in `load'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/bin/hanami:25:in `<main>'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/bin/ruby_executable_hooks:22:in `eval'
        from /home/senid/.rvm/gems/ruby-3.0.3@virtualizm/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by adam12** [comment]
@senid231 Hanami 1 doesn't support Ruby 3. Please try again with 2.7.

**Comment by senid231** [comment]
Thanks
